name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]



jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: source
        
    steps:
    - uses: actions/checkout@v2
    # Update references
    - name: Git Sumbodule Update
      run: |
        git pull origin main --recurse-submodules
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Update submodules
      run: git submodule update --recursive
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
